stages:
  - build
  - deploy

# Étape 1 : Build & Push du backend
build_backend:
  stage: build
  script:
    - docker build -t trulyahya/chatbot-backend ./chatbot-backend
    - echo "$DOCKERHUB_TOKEN" | docker login -u "trulyahya" --password-stdin
    - docker push trulyahya/chatbot-backend
  only:
    - main

# Étape 2 : Build & Push du frontend
build_frontend:
  stage: build
  script:
    - docker build -t trulyahya/chatbot-frontend ./chatbot-frontend
    - echo "$DOCKERHUB_TOKEN" | docker login -u "trulyahya" --password-stdin
    - docker push trulyahya/chatbot-frontend
  only:
    - main

# Étape 3 : Déploiement sur ton cluster EKS
deploy:
  stage: deploy
  script:
    - eksctl utils write-kubeconfig --cluster=chatbot-cluster --region us-east-1
    - kubectl apply -f backend-deployment.yaml
    - kubectl apply -f frontend-deployment.yaml
  only:
    - main

