stages:
  - build
  - deploy

# Étape 1 : Connexion Docker + Build & Push du backend
build_backend:
  stage: build
  script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "trulyahya" --password-stdin
    - docker build -t trulyahya/chatbot-backend ./chatbot-backend
    - docker push trulyahya/chatbot-backend
  only:
    - main

# Étape 2 : Build & Push du frontend
build_frontend:
  stage: build
  script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "trulyahya" --password-stdin
    - docker build -t trulyahya/chatbot-frontend ./chatbot-frontend
    - docker push trulyahya/chatbot-frontend
  only:
    - main

# Étape 3 : (optionnelle pour l’instant) Déploiement manuel
deploy:
  stage: deploy
  script:
    - echo "Déploiement manuel à faire plus tard"
  when: manual
  only:
    - main

