apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: trulyahya/chatbot-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080   # <-- ici on met 8080 (et non 5000)
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080          # <-- ici aussi on expose 8080
    targetPort: 8080    # <-- on mappe vers le port interne
  selector:
    app: backend
